# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jupyter-blog',
                'doc_host': 'https://scottsus.github.io',
                'git_url': 'https://github.com/scottsus/jupyter-blog',
                'lib_path': 'jupyter_blog'},
  'syms': {'jupyter_blog.core': {'jupyter_blog.core.foo': ('core.html#foo', 'jupyter_blog/core.py')}}}
